FROM ubuntu:python

ENV LANG pt_BR.utf8  
ENV LANGUAGE pt_BR.utf8  
ENV LC_ALL pt_BR.utf8 

EXPOSE 5000

COPY . /var/www/app
WORKDIR /var/www/app
    # ENTRYPOINT ["python3"]
    # CMD ["adaptive-dsd.py"]
